import { chromium } from '/Users/normy/autobyteus_org/autobyteus-web-design-worktrees/collapsed-left-panel-expand-keeps-run/node_modules/playwright-core/index.mjs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.log('PAGEERR', e.message));
await page.goto('http://127.0.0.1:4610/chat');
await page.evaluate(() => { localStorage.removeItem('autobyteus.prototype.scenario'); });
await page.goto('http://127.0.0.1:4610/workspace');
await page.waitForTimeout(2500);
await page.getByText('prototype-workspace', { exact: true }).first().click(); await page.waitForTimeout(400);
for (const sel of ['[data-test="workspace-team-definition-row-team-video"]','[data-test="workspace-team-row-team-run-video-0001"]']) { await page.click(sel); await page.waitForTimeout(1500); }
const dump = () => page.evaluate(() => [...document.querySelectorAll('[data-test="workspace-history-tree-scroll"] [role="treeitem"]')].map(b => (b.getAttribute('aria-level')||'') + ' :: ' + b.innerText.replace(/\s+/g,' ').trim().slice(0,40) + (b.getAttribute('aria-current')?' [CURRENT]':'')+(b.getAttribute('aria-expanded')?' exp='+b.getAttribute('aria-expanded'):'')).join('\n'));
console.log(await dump());
await page.screenshot({ path: '/tmp/clpe/s2-docked.png' });
await page.click('text=post_production'); await page.waitForTimeout(800);
console.log(await dump());
await page.getByText('colorist', { exact: true }).first().click(); await page.waitForTimeout(1500);
console.log(await dump());
await page.click('[data-test="app-left-panel-collapse"]'); await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/clpe/s2-colorist-collapsed.png' });
console.log('url before', page.url());
await page.screenshot({ path: '/tmp/clpe/s2-colorist-collapsed.png' });
await page.click('[data-test="workspace-left-strip-expand"]'); await page.waitForTimeout(1500);
console.log('url after', page.url());
console.log(await dump());
await page.screenshot({ path: '/tmp/clpe/s2-expanded.png' });
await browser.close();
