import { chromium } from '/Users/normy/autobyteus_org/autobyteus-web-design-worktrees/collapsed-left-panel-expand-keeps-run/node_modules/playwright-core/index.mjs';
const H = Number(process.argv[2] || 900);
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: H } });
page.on('pageerror', e => console.log('PAGEERR', e.message));
await page.goto('http://127.0.0.1:4610/workspace');
await page.waitForTimeout(2500);
await page.getByText('prototype-workspace', { exact: true }).first().click(); await page.waitForTimeout(400);
await page.click('[data-test="agent-org-definition-org-product-launch"]'); await page.waitForTimeout(800);
await page.click('[data-test="agent-org-run-open-org-run-001"]'); await page.waitForTimeout(2000);
await page.click('[data-test="agent-org-team-row-org-team-run-001"]'); await page.waitForTimeout(1500);
const dump = () => page.evaluate(() => [...document.querySelectorAll('[data-test="workspace-history-tree-scroll"] [role="treeitem"]')].map(b => (b.getAttribute('data-test')||'') + ' :: ' + b.innerText.replace(/\s+/g,' ').trim().slice(0,40) + (b.getAttribute('aria-current')==='true'||b.getAttribute('aria-selected')==='true'?' [SEL]':'')+(b.getAttribute('aria-expanded')?' exp='+b.getAttribute('aria-expanded'):'')).join('\n'));
console.log(await dump());
// open a member inside review team
const member = page.locator('[data-test^="agent-org-agent-row-"]').last();
console.log('member', await member.innerText());
await member.click(); await page.waitForTimeout(1500);
console.log(await dump()); console.log(page.url());
const header1 = await page.locator('main').first().innerText();
await page.click('[data-test="app-left-panel-collapse"]'); await page.waitForTimeout(400);
await page.screenshot({ path: `/tmp/clpe/s3-collapsed-${H}.png` });
await page.click('[data-test="workspace-left-strip-expand"]'); await page.waitForTimeout(1500);
console.log(page.url());
console.log(await page.evaluate(() => { const c=document.querySelector('[data-test="workspace-history-tree-scroll"]'); const rows=[...c.querySelectorAll('[aria-current="true"],[aria-selected="true"]')]; const b=c.getBoundingClientRect(); const r=rows.at(-1).getBoundingClientRect(); return {row: rows.at(-1).innerText.trim(), scrollTop: c.scrollTop, rowTop:r.top, rowBottom:r.bottom, boxTop:b.top, boxBottom:b.bottom, visible: r.top>=b.top && r.bottom<=b.bottom}; }));
console.log(await dump());
await page.screenshot({ path: `/tmp/clpe/s3-expanded-${H}.png` });
await browser.close();
