const shot = async (n) => { await page.waitForTimeout(500); await page.screenshot({ path: `/tmp/adr/j1-${n}.png` }) }
await page.getByText('prototype-workspace').first().click()
await page.waitForTimeout(800)
await page.locator('[data-agent-definition-id="tutorial-video-producer"]').first().click()
await page.waitForTimeout(400)
await page.getByText('Turn the v2 launch notes').first().click()
await page.waitForTimeout(1500)
await shot('a-open')
const box = page.locator('textarea').first()
await box.click(); await box.fill('Make the first cut.')
await box.press('Enter')
await page.waitForTimeout(1200)
await shot('b-error')
await page.locator('[data-test="agent-missing-error-reconnect"]').click()
await shot('c-dialog')
await page.locator('[data-test="reconnect-dialog-search"]').fill('video')
await shot('d-search')
await page.locator('[data-test="reconnect-dialog-search"]').fill('')
await page.locator('[data-test="reconnect-option-product-video-producer"]').click()
await shot('e-selected')
await page.locator('[data-test="reconnect-dialog-confirm"]').click()
await page.waitForTimeout(1200)
await shot('f-reconnected')
await box.click(); await box.fill('Make the first cut.')
await box.press('Enter')
await page.waitForTimeout(2200)
await shot('g-continued')
