const shot = async (n) => { await page.waitForTimeout(500); await page.screenshot({ path: `/tmp/adr/j2-${n}.png` }) }
await page.getByText('prototype-workspace').first().click()
await page.waitForTimeout(800)
await page.getByText('Video Team').first().click()
await page.waitForTimeout(500)
await page.getByText('Produce the v2 launch').first().click()
await page.waitForTimeout(1500)
await page.locator('[data-member-address="/editor"]').first().click()
await page.waitForTimeout(1200)
await shot('a-editor')
await page.locator('button[title*="onfig"], button[aria-label*="onfig"], button[title*="etting"], button[aria-label*="etting"]').first().click().catch(e => console.log('gear', e.message))
await page.waitForTimeout(1500)
await shot('b-settings')
await page.locator('[data-test^="existing-run-reconnect-team-video-editor"]').click()
await shot('c-dialog')
await page.locator('[data-test="reconnect-option-video-clip-editor"]').click()
await page.locator('[data-test="reconnect-dialog-confirm"]').click()
await page.waitForTimeout(1200)
await shot('d-settings-done')
await page.locator('[data-member-address="/tutorial_video_producer"]').first().click()
await page.waitForTimeout(1500)
await shot('e-collab')
const box = page.locator('textarea').first()
await box.click(); await box.fill('Tighten the storyboard to 60 seconds.')
await box.press('Enter')
await page.waitForTimeout(1200)
await shot('f-collab-error')
await page.locator('[data-test="agent-missing-error-reconnect"]').click()
await page.locator('[data-test="reconnect-option-product-video-producer"]').click()
await page.locator('[data-test="reconnect-dialog-confirm"]').click()
await page.waitForTimeout(1200)
await shot('g-collab-done')
await page.locator('[data-member-address="/editor"]').first().click()
await page.waitForTimeout(1200)
await shot('h-editor-after')
