const shot = async (n) => { await page.waitForTimeout(500); await page.screenshot({ path: `/tmp/adr/j4-${n}.png` }) }
await page.getByText('prototype-workspace').first().click()
await page.waitForTimeout(800)
await page.locator('[data-agent-definition-id="tutorial-video-producer"]').first().click()
await page.waitForTimeout(400)
await page.getByText('Turn the v2 launch notes').first().click()
await page.waitForTimeout(1500)
await page.locator('button[title*="onfig"], button[aria-label*="onfig"], button[title*="etting"], button[aria-label*="etting"]').first().click()
await page.waitForTimeout(1500)
await shot('a-settings-run')
await page.locator('[data-test^="existing-run-reconnect-run-tvp"]').click()
await page.waitForTimeout(300)
await page.keyboard.press('ArrowDown')
await page.keyboard.press('Enter')
await page.waitForTimeout(1500)
await shot('b-settings-done')
await page.locator('[data-agent-definition-id="agent-researcher"]').first().click()
await page.waitForTimeout(500)
await page.getByText('Compare current navigation').first().click()
await page.waitForTimeout(1500)
await shot('c-regression')
