const shot = async (n) => { await page.waitForTimeout(500); await page.screenshot({ path: `/tmp/adr/j5-${n}.png` }) }
await page.getByText('prototype-workspace').first().click()
await page.waitForTimeout(800)
await page.getByText('Video Team').first().click()
await page.waitForTimeout(500)
await page.getByText('Produce the v2 launch').first().click()
await page.waitForTimeout(1800)
console.log(JSON.stringify(await page.locator('[role="treeitem"]').allInnerTexts()))
await shot('a-tree')
await page.locator('[data-member-address="/tutorial_video_producer"]').first().click()
await page.waitForTimeout(1200)
await page.locator('[data-test="agent-missing-reconnect"]').click()
await page.locator('[data-test="reconnect-option-product-video-producer"]').click()
await page.locator('[data-test="reconnect-dialog-confirm"]').click()
await page.waitForTimeout(1500)
await shot('b-done')
console.log(JSON.stringify(await page.locator('[role="treeitem"]').allInnerTexts()))
await page.locator('button[title*="onfig"], button[aria-label*="onfig"], button[title*="etting"], button[aria-label*="etting"]').first().click()
await page.waitForTimeout(1500)
await shot('c-settings')
