await page.getByText('prototype-workspace').first().click()
await page.waitForTimeout(800)
await page.locator('[data-agent-definition-id="tutorial-video-producer"]').first().click()
await page.waitForTimeout(400)
await page.getByText('Turn the v2 launch notes').first().click()
await page.waitForTimeout(1500)
const box = page.locator('textarea').first(); await box.click(); await box.fill('Make the first cut.'); await box.press('Enter'); await page.waitForTimeout(1200)
await page.locator('[data-test="agent-missing-error-reconnect"]').click()
await page.locator('[data-test="reconnect-option-product-video-producer"]').click()
await page.locator('[data-test="reconnect-dialog-confirm"]').click()
await page.waitForTimeout(1500)
console.log('live:', await page.locator('[data-test="agent-missing-error-card-resolved"]').innerText())
await page.locator('[data-agent-definition-id="agent-researcher"]').first().click(); await page.waitForTimeout(400)
await page.getByText('Compare current navigation').first().click(); await page.waitForTimeout(1500)
await page.locator('[data-agent-definition-id="product-video-producer"]').first().click(); await page.waitForTimeout(400)
await page.getByText('Turn the v2 launch notes').first().click(); await page.waitForTimeout(1800)
console.log('reopened:', await page.locator('[data-test="agent-missing-error-card-resolved"]').innerText(), '| reconnect buttons:', await page.locator('[data-test="agent-missing-error-reconnect"]').count())
