import { chromium } from '/Users/normy/autobyteus_org/autobyteus-web-design-worktrees/collapsed-left-panel-expand-keeps-run/node_modules/playwright-core/index.mjs';
const base = 'http://127.0.0.1:4610';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => console.log('PAGEERR', e.message));
await page.goto(base + '/projects');
await page.waitForTimeout(2500);
await page.click('[data-test="app-left-panel-collapse"]');
await page.waitForTimeout(400);
console.log('focused after collapse:', await page.evaluate(() => document.activeElement?.getAttribute('data-test')));
await page.screenshot({ path: '/tmp/clpe/s1-projects-collapsed.png' });
await page.getByText('Prototype Launch').first().click();
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/clpe/s1-project.png' });
const workers = await page.$$('[data-testid^="project-task-worker-"]');
console.log('workers', workers.length, await Promise.all(workers.map(w => w.innerText())));
await workers[0].click();
await page.waitForTimeout(2500);
console.log('url before expand', page.url());
await page.screenshot({ path: '/tmp/clpe/s1-worker-open-collapsed.png' });
await page.hover('[data-test="workspace-left-strip-expand"]');
await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/clpe/s1-hover.png' });
await page.click('[data-test="workspace-left-strip-expand"]');
await page.waitForTimeout(1500);
console.log('url after expand', page.url());
console.log('focused after expand:', await page.evaluate(() => document.activeElement?.getAttribute('data-test')));
console.log(await page.evaluate(() => { const c=document.querySelector('[data-test="workspace-history-tree-scroll"]'); const rows=[...c.querySelectorAll('[aria-current="true"],[aria-selected="true"]')]; const b=c.getBoundingClientRect(); return rows.map(r=>{const x=r.getBoundingClientRect(); return {t:r.innerText.trim().slice(0,40), top:x.top, bottom:x.bottom, boxTop:b.top, boxBottom:b.bottom}}) }));
await page.screenshot({ path: '/tmp/clpe/s1-expanded.png' });
await browser.close();
